vich_uploader:
    db_driver: orm

    mappings:
        blog_image:
            uri_prefix: /uploads/blogs
            upload_destination: '%kernel.project_dir%/public/uploads/blogs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer